<?php
/**
 * CustomWatermarkSettingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomWatermarkSettingTest Class Doc Comment
 *
 * @category    Class */
// * @description List custom watermarks for a team
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomWatermarkSettingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomWatermarkSetting"
     */
    public function testCustomWatermarkSetting()
    {
    }

    /**
     * Test attribute "watermark_id"
     */
    public function testPropertyWatermarkId()
    {
    }

    /**
     * Test attribute "team_id"
     */
    public function testPropertyTeamId()
    {
    }

    /**
     * Test attribute "custom_text"
     */
    public function testPropertyCustomText()
    {
    }

    /**
     * Test attribute "color"
     */
    public function testPropertyColor()
    {
    }

    /**
     * Test attribute "opacity"
     */
    public function testPropertyOpacity()
    {
    }

    /**
     * Test attribute "font_size"
     */
    public function testPropertyFontSize()
    {
    }

    /**
     * Test attribute "rotation"
     */
    public function testPropertyRotation()
    {
    }

    /**
     * Test attribute "hposition"
     */
    public function testPropertyHposition()
    {
    }

    /**
     * Test attribute "vposition"
     */
    public function testPropertyVposition()
    {
    }

    /**
     * Test attribute "display_user_name"
     */
    public function testPropertyDisplayUserName()
    {
    }

    /**
     * Test attribute "display_user_email"
     */
    public function testPropertyDisplayUserEmail()
    {
    }

    /**
     * Test attribute "display_ip_address"
     */
    public function testPropertyDisplayIpAddress()
    {
    }

    /**
     * Test attribute "display_time"
     */
    public function testPropertyDisplayTime()
    {
    }

    /**
     * Test attribute "display_workspace_name"
     */
    public function testPropertyDisplayWorkspaceName()
    {
    }
}
