<?php
/**
 * GroupInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GroupInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Disable access expiration for a group
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GroupInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GroupInfo"
     */
    public function testGroupInfo()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "workspace_id"
     */
    public function testPropertyWorkspaceId()
    {
    }

    /**
     * Test attribute "drm_enabled"
     */
    public function testPropertyDrmEnabled()
    {
    }

    /**
     * Test attribute "drm_expires_after"
     */
    public function testPropertyDrmExpiresAfter()
    {
    }

    /**
     * Test attribute "expire_workspace_access"
     */
    public function testPropertyExpireWorkspaceAccess()
    {
    }

    /**
     * Test attribute "expire_workspace_access_at"
     */
    public function testPropertyExpireWorkspaceAccessAt()
    {
    }

    /**
     * Test attribute "watermarked"
     */
    public function testPropertyWatermarked()
    {
    }

    /**
     * Test attribute "file_managing_abilities"
     */
    public function testPropertyFileManagingAbilities()
    {
    }
}
