<?php
/**
 * TeamTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TeamTest Class Doc Comment
 *
 * @category    Class */
// * @description Get team information
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TeamTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Team"
     */
    public function testTeam()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "team_owner_id"
     */
    public function testPropertyTeamOwnerId()
    {
    }

    /**
     * Test attribute "creator_id"
     */
    public function testPropertyCreatorId()
    {
    }

    /**
     * Test attribute "allowed_workspaces"
     */
    public function testPropertyAllowedWorkspaces()
    {
    }

    /**
     * Test attribute "allowed_admins"
     */
    public function testPropertyAllowedAdmins()
    {
    }

    /**
     * Test attribute "drm_enabled"
     */
    public function testPropertyDrmEnabled()
    {
    }

    /**
     * Test attribute "watermarking"
     */
    public function testPropertyWatermarking()
    {
    }

    /**
     * Test attribute "suppress_emails"
     */
    public function testPropertySuppressEmails()
    {
    }
}
