<?php
/**
 * DownloadsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Caplinked
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Caplinked;

use \Caplinked\Configuration;
use \Caplinked\ApiClient;
use \Caplinked\ApiException;
use \Caplinked\ObjectSerializer;

/**
 * DownloadsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Caplinked
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DownloadsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteDownloadsId
     *
     * Delete download.
     *
     */
    public function testDeleteDownloadsId()
    {
    }

    /**
     * Test case for getDownloadsFileFileId
     *
     * Get single file.
     *
     */
    public function testGetDownloadsFileFileId()
    {
    }

    /**
     * Test case for getDownloadsId
     *
     * Get zip.
     *
     */
    public function testGetDownloadsId()
    {
    }

    /**
     * Test case for getDownloadsStatusWorkspaceId
     *
     * Get status of downloads for current user.
     *
     */
    public function testGetDownloadsStatusWorkspaceId()
    {
    }

    /**
     * Test case for postDownloads
     *
     * Create zip file.
     *
     */
    public function testPostDownloads()
    {
    }
}
