<?php
/**
 * FilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Caplinked
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Caplinked;

use \Caplinked\Configuration;
use \Caplinked\ApiClient;
use \Caplinked\ApiException;
use \Caplinked\ObjectSerializer;

/**
 * FilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Caplinked
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FilesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteFilesId
     *
     * Delete file.
     *
     */
    public function testDeleteFilesId()
    {
    }

    /**
     * Test case for getFilesId
     *
     * Get file information.
     *
     */
    public function testGetFilesId()
    {
    }

    /**
     * Test case for postFilesIdCopy
     *
     * Copy file.
     *
     */
    public function testPostFilesIdCopy()
    {
    }

    /**
     * Test case for postFilesIdMove
     *
     * Move file.
     *
     */
    public function testPostFilesIdMove()
    {
    }

    /**
     * Test case for putFilesId
     *
     * Update file information.
     *
     */
    public function testPutFilesId()
    {
    }

    /**
     * Test case for putFilesUpload
     *
     * Upload file.
     *
     */
    public function testPutFilesUpload()
    {
    }
}
