<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteGroupsId
     *
     * Delete group.
     *
     */
    public function testDeleteGroupsId()
    {
    }

    /**
     * Test case for deleteGroupsIdMemberships
     *
     * Remove a user from a group.
     *
     */
    public function testDeleteGroupsIdMemberships()
    {
    }

    /**
     * Test case for getGroups
     *
     * List all groups in workspace.
     *
     */
    public function testGetGroups()
    {
    }

    /**
     * Test case for getGroupsId
     *
     * Get group information.
     *
     */
    public function testGetGroupsId()
    {
    }

    /**
     * Test case for getGroupsIdMemberships
     *
     * List all memberships for a group.
     *
     */
    public function testGetGroupsIdMemberships()
    {
    }

    /**
     * Test case for postGroups
     *
     * Create group.
     *
     */
    public function testPostGroups()
    {
    }

    /**
     * Test case for postGroupsIdMemberships
     *
     * Add user to group (adds to parent workspace if they are not already a member).
     *
     */
    public function testPostGroupsIdMemberships()
    {
    }

    /**
     * Test case for putGroupsId
     *
     * Update group.
     *
     */
    public function testPutGroupsId()
    {
    }

    /**
     * Test case for putGroupsIdDisableDrmExpiration
     *
     * Disable DRM expiration for group.
     *
     */
    public function testPutGroupsIdDisableDrmExpiration()
    {
    }

    /**
     * Test case for putGroupsIdDisableExpireAccess
     *
     * Disable access expiration for a group.
     *
     */
    public function testPutGroupsIdDisableExpireAccess()
    {
    }

    /**
     * Test case for putGroupsIdDrm
     *
     * Update DRM for group.
     *
     */
    public function testPutGroupsIdDrm()
    {
    }

    /**
     * Test case for putGroupsIdEnableExpireAccess
     *
     * Enable access expiration for a group.
     *
     */
    public function testPutGroupsIdEnableExpireAccess()
    {
    }

    /**
     * Test case for putGroupsIdWatermarking
     *
     * Watermarking for group.
     *
     */
    public function testPutGroupsIdWatermarking()
    {
    }
}
