<?php
/**
 * OrganizationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * OrganizationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrganizationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteOrganizationMemberships
     *
     * Remove organization admin membership.
     *
     */
    public function testDeleteOrganizationMemberships()
    {
    }

    /**
     * Test case for getOrganization
     *
     * Get organization information.
     *
     */
    public function testGetOrganization()
    {
    }

    /**
     * Test case for getOrganizationMemberships
     *
     * Show all organization members.
     *
     */
    public function testGetOrganizationMemberships()
    {
    }

    /**
     * Test case for postOrganizationMemberships
     *
     * Add organization admin membership.
     *
     */
    public function testPostOrganizationMemberships()
    {
    }

    /**
     * Test case for putOrganization
     *
     * Update organization information.
     *
     */
    public function testPutOrganization()
    {
    }

    /**
     * Test case for putOrganizationSupportInformation
     *
     * Update support information of organization.
     *
     */
    public function testPutOrganizationSupportInformation()
    {
    }
}
