<?php
/**
 * TeamsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Caplinked
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CapLinked API v1.0
 *
 * Core information security endpoints for managing files/folders, users/groups, uploads/downloads, and more.
 *
 * OpenAPI spec version: 2017-05-23
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Caplinked;

use \Caplinked\Configuration;
use \Caplinked\ApiClient;
use \Caplinked\ApiException;
use \Caplinked\ObjectSerializer;

/**
 * TeamsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Caplinked
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeamsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteTeamsIdMemberships
     *
     * Remove team member.
     *
     */
    public function testDeleteTeamsIdMemberships()
    {
    }

    /**
     * Test case for getTeams
     *
     * List all teams in organization.
     *
     */
    public function testGetTeams()
    {
    }

    /**
     * Test case for getTeamsId
     *
     * Get team information.
     *
     */
    public function testGetTeamsId()
    {
    }

    /**
     * Test case for getTeamsIdMemberships
     *
     * Get list of team members.
     *
     */
    public function testGetTeamsIdMemberships()
    {
    }

    /**
     * Test case for getTeamsIdWatermarkSettings
     *
     * List custom watermarks for a team.
     *
     */
    public function testGetTeamsIdWatermarkSettings()
    {
    }

    /**
     * Test case for postTeams
     *
     * Create team.
     *
     */
    public function testPostTeams()
    {
    }

    /**
     * Test case for postTeamsIdMemberships
     *
     * Add team member.
     *
     */
    public function testPostTeamsIdMemberships()
    {
    }

    /**
     * Test case for putTeamsId
     *
     * Update team.
     *
     */
    public function testPutTeamsId()
    {
    }
}
